### ISSUE TITLE
Safari highlights icon instead of whole button

### ISSUE THREAD

**Issue by jdnavarro** [IBM/carbon-icons-svelte#93]
On iOS Safari when tapping an icon that's inside a button, the icon gets highlighted instead of the whole button.

When [removing the event forwarders](https://github.com/feral-bunch/carbon-icons-svelte/commit/e9d000cbbe5fbae4f9064e787774f909a60c408f#diff-a875f0630e8a46d5a0e706a94502051f5a75e669312987096e4f52941b2bf476L35-L40) the glitch goes away.

I tried to pass the event modifiers `preventDefault` and `stopPropagation` and removing all Safari builtin styling for focused elements, but still no luck.
 
Keyboard events are fine, this is only affected by mouse events.

**Comment by metonym** [comment]
Can you provide some sample markup code so that I can reproduce the bug?

**Comment by jdnavarro** [comment]
You should be able to reproduce it from the official examples. For example, I can see it on the [Icon-only button](https://carbon-svelte.vercel.app/components/Button#icon-only-button).

Notice how the highlighted area is different when tapping the `plus` sign directly vs tapping anywhere else on the button. The glitch is more conspicuous with a ghost button, but it's still appreciable on a primary button.

I have only seen this issue on iOS. I don't have a MacOS machine at hand at the moment, but on [Gnome Web](https://en.wikipedia.org/wiki/GNOME_Web), using the latest version of WebKit, I can't reproduce it, so it may be iOS specific.

**Comment by metonym** [comment]
Thank you, I'll take a look

**Comment by metonym** [comment]
@jdnavarro Indeed, on iOS Safari, there is a tap highlight color caused by the forwarded click events, as you suggested.

As a temporary workaround, I would suggest adding this CSS to make the tap color transparent:

```css
svg { -webkit-tap-highlight-color: rgba(0, 0, 0, 0); }
```

Removing the forwarded events would be a breaking change. However, I do plan to remove the events anyway in the next major release. We already do this in [carbon-pictograms-svelte version 11](https://github.com/IBM/carbon-pictograms-svelte).

**Comment by jdnavarro** [comment]
The CSS tip works great. I'm glad I won't have to keep around my carbon icons fork anymore :sweat_smile:. Thanks @metonym.
